### ISSUE TITLE
Training model: Missing protobuf file

### ISSUE THREAD

**Issue by idobrusin** [linjieyangsc/densecap#1]
When following the instructions in the README to train a model the `dense_cap_train.sh` throws an error.

```
[...]
models/dense_cap/solver_joint_inference.prototxt
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1026 16:31:58.601896  5156 io.cpp:36] Check failed: fd != -1 (-1 vs. -1) File not found: models/dense_cap/solver_joint_inference.prototxt
```

The file models/dense_cap/solver_joint_inference.prototxt appears to be missing. I simply renamed the `solver_joint_inference_finetune.prototxt` file in order to train the model but I am not sure whether this is the correct approach. 

Is it possible to use the `solver_joint_inference_finetune.prototxt` file? If not, could you publish the correct file?

**Comment by linjieyangsc** [comment]
Hi, I have added the missing prototxt file. Please take a look. Thanks!
