### ISSUE TITLE
how to get object class like faster-rcnn (object name e.g. person or car) with other informations

### ISSUE THREAD

**Issue by Alireza-Mirhabibi** [linjieyangsc/densecap#6]
Hi
Dear Linjie,

I want to get class names before captioning (e.g. women or man and etc) is this possible to show me an example to do that in this project?
is there any variable in ./lib/tools/demo.py (fast_rcnn/test.py) in densecap project or I need to implant py-faster-rcnn into this project ?

**I will appreciate you if you help me to get object classes in densecap project.**

Thank you so much.

**Comment by Alireza-Mirhabibi** [comment]
Is anybody here?

**Comment by Alireza-Mirhabibi** [comment]
Is anybody here?

**Comment by linjieyangsc** [comment]
@Alireza-Mirhabibi we do not predict object categories for the DenseCap algorithm so it cannot be obtained with the current framework. One thing worth trying is to add a classification branch to the model and train the model with category annotations.
